authorName: Moerk
experimentName: 412 argtest
trialConcurrency: 1
maxExecDuration: 12h
maxTrialNum: 256
trainingServicePlatform: local
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  builtinTunerName: Random
assessor:
  builtinAssessorName: Curvefitting
  classArgs:
    epoch_num: 8
    start_step: 4
    threshold: 0.8
    gap: 1
trial:
  command: python main.py
  codeDir: .
localConfig:
  useActiveGpu: true

